### ISSUE TITLE
[Feature]: Progress bar for download a central's page.

### ISSUE THREAD

**Issue by Jogana3** [CorefluxCommunity/Coreflux-roadmap#10]
### Tell us about your request

I would like to see the progress of the download when you click install button in the HUB,

### Which component(s) is this request for?

- [ ] Coreflux Broker
- [X] Coreflux Hub
- [ ] Flux Assets
- [ ] Flux Language
- [ ] Power Ups
- [ ] User Experience (UX)
- [ ] Documentation
- [ ] Conceptual Features

### Is your feature request related to a problem? Please describe.

There is no clear state of the downloading process in the interface right now.

### Describe the solution you'd like

I should see a bar showing the percentage of downloading and change when the download of central finished.

### Is this request for a new asset?

no

**Comment by HugoAVaz** [comment]
This is done in release [Coreflux Hub v.1.2005 Release notes](https://github.com/CorefluxCommunity/Coreflux-roadmap/issues/11)
