### ISSUE TITLE
[Feature]: Delete login history and central installed files when a new version of the HUB is executed.

### ISSUE THREAD

**Issue by Jogana3** [CorefluxCommunity/Coreflux-roadmap#11]
### Tell us about your request

Delete those files in every HUB update.

### Which component(s) is this request for?

- [ ] Coreflux Broker
- [X] Coreflux Hub
- [ ] Flux Assets
- [ ] Flux Language
- [ ] Power Ups
- [ ] User Experience (UX)
- [ ] Documentation
- [ ] Conceptual Features

### Is your feature request related to a problem? Please describe.

Compatibility problems when you change the HUB for a newer version.

### Describe the solution you'd like

Detect if the HUB has executed for first time, search for login and central files and then delete them, leaving the directory clean of those files' old version.

**Comment by HugoAVaz** [comment]
We need to also add something for the user to confirm if he wants to remove or not the files. Providing a choice for the user he is able to decide. It might happen we remove assets and that creates an issue for the user.

**Comment by HugoAVaz** [comment]
Some of the effects happening from version v.1.2.001
![WhatsApp Image 2023-11-11 at 12 37 25_9ba165c7](https://github.com/CorefluxCommunity/Coreflux-roadmap/assets/60146011/83828ac3-909e-4976-adf1-c1627495424e)

**Comment by HugoAVaz** [comment]
Please verify the release notes for Coreflux Hub
[Coreflux Hub v.1.2.005](
https://docs.coreflux.org/release-notes/hub/#version-12005)
