### ISSUE TITLE
[Feature]: Button to delete an access in Hub Access 

### ISSUE THREAD

**Issue by Jogana3** [CorefluxCommunity/Coreflux-roadmap#12]
### Tell us about your request

A button to delete a Hub Access.

### Which component(s) is this request for?

- [ ] Coreflux Broker
- [X] Coreflux Hub
- [ ] Flux Assets
- [ ] Flux Language
- [ ] Power Ups
- [ ] User Experience (UX)
- [ ] Documentation
- [ ] Conceptual Features

### Describe the solution you'd like

The button should delete that access data in the login history file and not show anymore.

**Comment by Jogana3** [comment]
This is a preview of the delete button:

![image](https://github.com/CorefluxCommunity/Coreflux-roadmap/assets/64289121/a5d61358-daa9-44cc-aa39-3f04f0cc34ea)

**Comment by HugoAVaz** [comment]
This is done in version v.1.2.005 [Release Notes Coreflux Hub](https://docs.coreflux.org/release-notes/hub/#version-12005)
