### ISSUE TITLE
[Feature]: Import and Export config as a JSON File

### ISSUE THREAD

**Issue by Jogana3** [CorefluxCommunity/Coreflux-roadmap#19]
### Tell us about your request

Import a complete config for an asset as a JSON file and export mine too.

### Which component(s) is this request for?

- [ ] Coreflux Broker
- [X] Coreflux Hub
- [ ] Flux Assets
- [ ] Flux Language
- [ ] Power Ups
- [ ] User Experience (UX)
- [ ] Documentation
- [ ] Conceptual Features

### Describe the solution you'd like

User can export and import an asset's config as a JSON file

**Comment by Jogana3** [comment]
![image](https://github.com/CorefluxCommunity/Coreflux-roadmap/assets/64289121/ce855781-6fc3-4ad6-8a58-b59ccbd5288a)
![image](https://github.com/CorefluxCommunity/Coreflux-roadmap/assets/64289121/8ee8307a-3cee-49e5-ad82-060bd0bef0a9)

**Comment by HugoFelgueiras** [comment]
This is really a great change in Coreflux Hub. In this way I can backup my asset configurations or if I have a standard device I can just replicate the configuration in different customers.

**Comment by CarlosSous** [comment]
Really useful. With that feature i can import in one time all config. Imagine you have 1000 tags to configure, first you prepare the json file, after you import the config.
🔝🔝🔝love it❤️❤️

**Comment by HugoAVaz** [comment]
@Jogana3 What would be the version number for this feature?

**Comment by Jogana3** [comment]
> @Jogana3 What would be the version number for this feature?
Would be version 1.2.006
