### ISSUE TITLE
[Feature]: New working directory.

### ISSUE THREAD

**Issue by fiddlydigit** [CorefluxCommunity/Coreflux-roadmap#7]
### Tell us about your request

Change working directory for Coreflux Hubless.

### Which component(s) is this request for?

- [X] Coreflux Broker
- [ ] Coreflux Hub
- [X] Flux Assets
- [ ] Flux Language
- [X] Power Ups
- [X] User Experience (UX)
- [ ] Documentation
- [ ] Conceptual Features

### Is your feature request related to a problem? Please describe.

_/usr/share/Coreflux/data/<assetguid>_ requires `chmod` in order to make an asset executable.

### Describe the solution you'd like

-  Linux

Instead of using _/usr/share/Coreflux_ :

~/.local/bin/Coreflux (for user install)
or
/usr/local (admin install)

Since _/usr/local_ is included in standard system `PATH`, any future requirement to call executable will be covered.

- Windows

C:\Users\[YourUsername]\AppData\Local\ (?)

### Is this request for a new asset?

Any newly installed asset.

**Comment by HugoAVaz** [comment]
For a server/container/pod perspective it makes total sense . 
For Windows it would be hard to check an installed server . I think the hub will require a new feature to extend the log via remote or local machine .
